'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by SpecFlow (https://www.specflow.org/).
'     SpecFlow Version:3.9.0.0
'     SpecFlow Generator Version:3.9.0.0
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
#Region "Designer generated code"
'#pragma warning disable
Imports TechTalk.SpecFlow
Imports System
Imports System.Linq

Namespace Global.Delinea_Test_Automation.Features
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0"),  _
     System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     NUnit.Framework.TestFixtureAttribute(),  _
     NUnit.Framework.DescriptionAttribute("Google Search")>  _
    Partial Public Class GoogleSearchFeature
        
        Private testRunner As TechTalk.SpecFlow.ITestRunner
        
        Private Shared featureTags() As String = CType(Nothing,String())
        
#ExternalSource("DelineaSearch.feature",1)
#End ExternalSource
        
        <NUnit.Framework.OneTimeSetUpAttribute()>  _
        Public Overridable Sub FeatureSetup()
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner
            Dim featureInfo As TechTalk.SpecFlow.FeatureInfo = New TechTalk.SpecFlow.FeatureInfo(New System.Globalization.CultureInfo("en-US"), "Features", "Google Search", "  Como usuario"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  Quiero buscar en Google"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  Para validar que aparece Delinea en "& _ 
                    "los resultados", ProgrammingLanguage.VB, featureTags)
            testRunner.OnFeatureStart(featureInfo)
        End Sub
        
        <NUnit.Framework.OneTimeTearDownAttribute()>  _
        Public Overridable Sub FeatureTearDown()
            testRunner.OnFeatureEnd
            testRunner = Nothing
        End Sub
        
        <NUnit.Framework.SetUpAttribute()>  _
        Public Sub TestInitialize()
        End Sub
        
        <NUnit.Framework.TearDownAttribute()>  _
        Public Sub TestTearDown()
            testRunner.OnScenarioEnd
        End Sub
        
        Public Sub ScenarioInitialize(ByVal scenarioInfo As TechTalk.SpecFlow.ScenarioInfo)
            testRunner.OnScenarioInitialize(scenarioInfo)
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs(Of NUnit.Framework.TestContext)(NUnit.Framework.TestContext.CurrentContext)
        End Sub
        
        Public Sub ScenarioStart()
            testRunner.OnScenarioStart
        End Sub
        
        Public Sub ScenarioCleanup()
            testRunner.CollectScenarioErrors
        End Sub
        
        <NUnit.Framework.TestAttribute(),  _
         NUnit.Framework.DescriptionAttribute("Buscar Delinea en Google")>  _
        Public Sub BuscarDelineaEnGoogle()
            Dim tagsOfScenario() As String = CType(Nothing,String())
            Dim argumentsOfScenario As System.Collections.Specialized.OrderedDictionary = New System.Collections.Specialized.OrderedDictionary()
            Dim scenarioInfo As TechTalk.SpecFlow.ScenarioInfo = New TechTalk.SpecFlow.ScenarioInfo("Buscar Delinea en Google", Nothing, tagsOfScenario, argumentsOfScenario, featureTags)
#ExternalSource("C:\Users\jaird\source\repos\Delinea-Test-Automation\Delinea-Test-Automation\Features\DelineaSearch.feature",6)
  Me.ScenarioInitialize(scenarioInfo)
#End ExternalSource
            If (TagHelper.ContainsIgnoreTag(tagsOfScenario) OrElse TagHelper.ContainsIgnoreTag(featureTags)) Then
                testRunner.SkipScenario
            Else
                Me.ScenarioStart
#ExternalSource("C:\Users\jaird\source\repos\Delinea-Test-Automation\Delinea-Test-Automation\Features\DelineaSearch.feature",7)
    testRunner.Given("Here en Google Page", CType(Nothing,String), CType(Nothing,TechTalk.SpecFlow.Table), "Given ")
#End ExternalSource
#ExternalSource("C:\Users\jaird\source\repos\Delinea-Test-Automation\Delinea-Test-Automation\Features\DelineaSearch.feature",8)
    testRunner.When("busco ""Delinea""", CType(Nothing,String), CType(Nothing,TechTalk.SpecFlow.Table), "When ")
#End ExternalSource
#ExternalSource("C:\Users\jaird\source\repos\Delinea-Test-Automation\Delinea-Test-Automation\Features\DelineaSearch.feature",9)
    testRunner.Then("deber�a ver ""delinea.com/es"" en los resultados", CType(Nothing,String), CType(Nothing,TechTalk.SpecFlow.Table), "Then ")
#End ExternalSource
            End If
            Me.ScenarioCleanup
        End Sub
    End Class
End Namespace
'#pragma warning restore
#End Region
